#! /bin/bash

# new-tool.sh
#
# Script to create a new tool directory with boilerplate files. See CONTRIBUTING.md
# for details.
#
# Copyright (C) 2025 Alessandro Iepure
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

POTFILES="po/POTFILES"
TEMP_POTFILES=$(mktemp)

# Find all relevant files and check for translatable content
find src -type f \( -name "*.blp" -o -name "*.rs" -o -name "*.ui" \) | while read -r file; do
    case "$file" in
        *.blp|*.ui)
            # Check for _("...") pattern in blueprint/UI files
            if grep -q '_("' "$file" 2>/dev/null; then
                echo "$file"
            fi
            ;;
        *.rs)
            # Check for gettext usage in Rust files
            if grep -q -E '(gettext|ngettext|pgettext)\(' "$file" 2>/dev/null; then
                echo "$file"
            fi
            ;;
    esac
done >> "$TEMP_POTFILES"

# Add metadata files
find data -maxdepth 2 -type f \( -name "*.metainfo.xml*" -o -name "*.appdata.xml*" \) 2>/dev/null >> "$TEMP_POTFILES" || true

# Add desktop files
find data -maxdepth 2 -type f -name "*.desktop.in*" 2>/dev/null >> "$TEMP_POTFILES" || true

# Add gschema files
find data -maxdepth 2 -type f -name "*.gschema.xml" 2>/dev/null >> "$TEMP_POTFILES" || true

# Sort alphabetically and remove duplicates, then add header
{
    echo "# Dev Toolbox - Translatable files"
    echo "# DO NOT EDIT MANUALLY. This file is auto-generated by gen-po.sh"
    echo ""
    sort -u "$TEMP_POTFILES"
} > "$POTFILES"

# Clean up
rm "$TEMP_POTFILES"

echo "Generated $POTFILES with $(wc -l < "$POTFILES") files"

# Regenerate translation templates in flatpak build terminal
flatpak build --with-appdir --allow=devel .flatpak/repo bash -lc "ninja -C _build devtoolbox-pot" 
flatpak build --with-appdir --allow=devel .flatpak/repo bash -lc "ninja -C _build devtoolbox-update-po"
