#! /bin/sh
# Copyright (C) 2022 - 2025 Alessandro Iepure
#
# SPDX-License-Identifier: GPL-3.0-or-later

if [ -n "$XDG_RUNTIME_DIR" ] && [ -d "$XDG_RUNTIME_DIR" ]; then
	mkdir -p "$XDG_RUNTIME_DIR/app/me.iepure.devtoolbox"
	export TMPDIR="$XDG_RUNTIME_DIR/app/me.iepure.devtoolbox"
fi
exec /app/bin/devtoolbox-bin "$@"
